### ISSUE TITLE
Statuses and codes conversions

### ISSUE THREAD

**Issue by ValentineHerr** [VincyaneBadouard/TreeData#44]
This is a first sketch of ideas for dealing with Statuses and Code, and I need feedback about this @gabrielareto, @cpiponiot and @VincyaneBadouard  

## Basic Alive vs Dead  --> `LifeStatus`, logical TRUE/FALSE

We are already doing this by asking: **"What column stores the information about whether a tree is dead or alive?"**, and then asking, "**in that column, which code(s) represent a tree that is alive?**" 
We should **_be more specific_** about this an maybe saying:
- **TRUE = Alive  = any measurable living tree** by opposition, anything that does not have the code specified, will be considered as 
- **FALSE = Dead = Dead or not available for inventory**, so, e.g. a **tree broken below will be considered as Dead.**

## Live Codes --> `LiveCodes`
character codes indicating things about a tree that is alive (e.g. leaning, unhealthy, etc...)
 
## Dead Codes --> `DeadCodes`
character codes indicating things about a tree that is dead or not avaibable for census (e.g. mode of death, broken below, not found etc...)

----------------
Then the idea would be to have the user enter the meaning of each `LiveCodes `and `DeadCodes` and work on making the connexion with the output's codes.... 
that would be a pretty big and tedious work but might be worth the effort...

**Comment by gabrielareto** [comment]
LifeStatus should be TRUE/FALSE = alive / dead. This is the most important aspect that we may want to store. We should not mix this important variable (inherently binary) with other types of information. I.e. a tree broken at 1.29 m should NOT be encoded as "dead" here.

some people keep codes that mean "there is a good reason why DBH = NA" or "there is a good reason why DBH = 0 mm". This may be relevant for us because in the correction step we may input missing DBHs or fit models for growth, etc. Other than that, the "broken below" code is not different to other status codes like "it is leaning", "it is infested by lianas", etc. It is not appropriate to try to fit it into the LifeStatus code.

we would solve many problems if we find the way to allow mapping between [all categories in the network variables] and [all categories in the user's variables]. Categories can be distributed into one or more variables, both in the user data or the network format.

**Comment by cpiponiot** [comment]
I think a mix of predefined codes and custom options is the best solution. We could define 10-20 common codes with the working group. We can first gather this information from the data dictionaries (Gabriel or I could do this), come up with a first selection, and then discuss it with everyone.

**Comment by ValentineHerr** [comment]
Thanks @cpiponiot for the feedback!
I started a first set of codes [here](https://github.com/VincyaneBadouard/TreeData/blob/master/inst/app/data/CodeOptions.csv). Feel free to modify.
I added the column "Source" just so wee know where the definition is coming from but it si not required to fill that up if we make our own definitions.

**Comment by ValentineHerr** [comment]
Closing this, as it is done. It needs testing but  we can open new issues if that are problems
