### ISSUE TITLE
better example of dates in app

### ISSUE THREAD

**Issue by ValentineHerr** [VincyaneBadouard/TreeData#76]
make sure the dates that are shown are different and with some value > 12 so it is clear what is month vs days

**Comment by gabrielareto** [comment]
you would need to look for "13", "14", "15", etc. as characters. Do not make this strict. We do not want the whole app to fail if someone keeps things like "nov 1999" instead of full dates. If you do not find "13", "14", "15", etc. then show data[few random rows, date column]

matches <- unique(grep(paste(13:31,collapse="|"), the whole column with the dates, value=TRUE))
show <- sample(c(matches, 5 random rows))[1:5]
